#:import NoTransition kivy.uix.screenmanager.NoTransition

<MainScreenManager@ScreenManager>
    transition: NoTransition()

    Screen:
        name: "greetings"
        GreetingsScreen:
            main_manager: root

    Screen:
        name: "login"
        LogInScreen:
            main_manager: root

    Screen:
        name: "sidebar_screen"
        SidebarScreen:
            main_manager: root