#:import FadeTransition kivy.uix.screenmanager.FadeTransition

<MainScreenManager@ScreenManager>
    transition: FadeTransition()

    Screen:
        name: "greetings"
        GreetingsScreen:
            main_manager: root

    Screen:
        name: "login"
        LogInScreen:
            main_manager: root

    Screen:
        name: "sidebar_screen"
        SidebarScreen:
            main_manager: root